#ifndef PARSER_TABLE_CPP
#define PARSER_TABLE_CPP

#include "./ParserTable.h"

vector<string> PredictiveParserTable::get_next_production(string lhs, string incoming_token) {
    int row = -1;
    int col = -1;

    try {
        row = NONTERMINAL_TO_ROW.at(lhs);
        col = LEXEME_TO_COL.at(incoming_token);
    } catch (const std::out_of_range& oor) {
        std::cerr << "Out of Range error in PARSER_TABLE: " << oor.what() << '\n';
        return vector<string>();
    }

    return PREDICTIVE_PARSER_TABLE[row][col];
}

// predictive parser table column dicitonary
const unordered_map<string, int> PredictiveParserTable::LEXEME_TO_COL {
    // GENERALIZED TERMINALS
    { "IDENTIFIER", 1 }, { "INTEGER", 2 }, { "REAL", 3 },
    
    // KEYWORDS
    { "function", 0 }, { "int", 4 }, { "boolean", 5 }, { "real", 6 }, { "if", 13 }, { "else", 14 }, { "endif", 15 }, {"return", 16}, { "put", 17 }, { "get", 18 }, { "while", 19 },

    // BOOLEAN VALUE
    { "true", 20 }, { "false", 21 },

    // OPERATORS
    { "+", 22 }, { "-", 23 }, { "*", 24 }, { "/", 25 }, { "==", 26 }, { "^=", 27 }, { ">", 28 }, { "<", 29 }, { "=>", 30 }, { "=<", 31 },

    // SEPARATORS
    { "{", 7 }, { "}", 8}, { "(", 9 }, { ")", 10 }, { "[", 11 }, { "]", 12 }, { ":", 32 }, { ";", 33 }, { ",", 34 }, { "%", 35 }, { "$", 36 }
};

const unordered_map<string, int> PredictiveParserTable::NONTERMINAL_TO_ROW {
    {"<Rat23S>"  ,                       0 },
    {"<Opt Function Definitions>"  ,     1 },
    {"<Function Definitions>"  ,         2 },
    {"<Function Definitions>\'",         3 },
    {"<Function>"  ,                     4 },
    {"<Opt Parameter List>"  ,           5 },
    {"<Parameter List>"  ,               6 },
    {"<Parameter List>'",                7 },
    {"<Parameter>"  ,                    8 },
    {"<Qualifier>"  ,                    9 },
    {"<Body>"  ,                        10 },
    {"<Opt Declaration List>"  ,        11 },
    {"<Declaration List>"  ,            12 },
    {"<Declaration List>\'",            13 },
    {"<Declaration>"  ,                 14 },
    {"<IDs>"  ,                         15 },
    {"<IDs>\'",                         16 },
    {"<Statement List>"  ,              17 },
    {"<Statement List>\'",              18 },
    {"<Statement>"  ,                   19 },
    {"<Compound>"  ,                    20 },
    {"<Assign>"  ,                      21 },
    {"<If>"  ,                          22 },
    {"<If>\'",                          23 },
    {"<Return>"  ,                      24 },
    {"<Return>\'",                      25 },
    {"<Print>"  ,                       26 },
    {"<Scan>"  ,                        27 },
    {"<While>"  ,                       28 },
    {"<Condition>"  ,                   29 },
    {"<Relop>"  ,                       30 },
    {"<Expression>"  ,                  31 },
    {"<Expression>\'",                  32 },
    {"<Term>"  ,                        33 },
    {"<Term>\'",                        34 },
    {"<Factor>"  ,                      35 },
    {"<Primary>"  ,                     36 },
    {"<Primary>\'",                     37 },
};

const vector<vector<vector<string>>> PredictiveParserTable::PREDICTIVE_PARSER_TABLE = {
/* ROW_INDEX \ COL_INDEX                        {   0                                                                                                   1,                                              2,                                              3,                                              4,                                                  5,                                                  6,                                                  7,                                          8,              9,                                              10,             11,     12,             13,                                                         14,                                 15,         16,                                         17,                                         18,                                         19,                                                     20,                                             21,                                             22,                                     23,                                             24,                                 25,                                 26,             27,             28,             29,             30,             31,             32,             33,             34,                 35,                                                                                         36                  } */
/* ROW[00] - <Rat23S>  */                       {   { "<Opt Function Definitions>", "%", "%", "<Opt Declaration List>", "<Statement List>"  },          {},                                             {},                                             {},                                             {},                                                 {},                                                 {},                                                 {},                                         {},             {},                                             {},             {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                 { "<Opt Function Definitions>", "%", "%", "<Opt Declaration List>", "<Statement List>" },   { "<Empty>" },      },
/* ROW[01] - <Opt Function Definitions>  */     {   { "<Function Definitions>"  },                                                                      {},                                             {},                                             {},                                             {},                                                 {},                                                 {},                                                 {},                                         {},             {},                                             {},             {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                 { "<Empty>" },                                                                              {},                 },
/* ROW[02] - <Function Definitions>  */         {   { "<Function>", "<Function Definitions>\'" },                                                       {},                                             {},                                             {},                                             {},                                                 {},                                                 {},                                                 {},                                         {},             {},                                             {},             {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                 {},                                                                                         {},                 },
/* ROW[03] - <Function Definitions>' */         {   { "<Function Definitions>" },                                                                       {},                                             {},                                             {},                                             {},                                                 {},                                                 {},                                                 {},                                         {},             {},                                             {},             {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                 { "<Empty>" },                                                                              {},                 },
/* ROW[04] - Function  */                       {   { "function", "IDENTIFIER", "[", "<Opt Parameter List>", "]", "<Opt Declaration List>", "<Body>"},  {},                                             {},                                             {},                                             {},                                                 {},                                                 {},                                                 {},                                         {},             {},                                             {},             {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                 {},                                                                                         {},                 },
/* ROW[05] - <Opt Parameter List>  */           {   {},                                                                                                 { "<Parameter List>" },                         {},                                             {},                                             {},                                                 {},                                                 {},                                                 {},                                         {},             {},                                             {},             {},     { "<Empty>" },  {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                 {},                                                                                         {},                 },
/* ROW[06] - <Parameter List>  */               {   {},                                                                                                 { "<Parameter>", "<Parameter List>'" },         {},                                             {},                                             {},                                                 {},                                                 {},                                                 {},                                         {},             {},                                             {},             {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                 {},                                                                                         {},                 },
/* ROW[07] - <Parameter List>' */               {   {},                                                                                                 { "<Parameter List>" },                         {},                                             {},                                             {},                                                 {},                                                 {},                                                 {},                                         {},             {},                                             {},             {},     { "<Empty>" },  {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                 {},                                                                                         {},                 },
/* ROW[08] - <Parameter>  */                    {   {},                                                                                                 { "<IDs>", ":", "<Qualifier>" },                {},                                             {},                                             {},                                                 {},                                                 {},                                                 {},                                         {},             {},                                             {},             {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                 {},                                                                                         {},                 },
/* ROW[09] - <Qualifier>  */                    {   {},                                                                                                 {},                                             {},                                             {},                                             { "int" },                                          { "boolean" },                                      { "real" },                                         {},                                         {},             {},                                             {},             {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                 {},                                                                                         {},                 },
/* ROW[10] - <Body>  */                         {   {},                                                                                                 {},                                             {},                                             {},                                             {},                                                 {},                                                 {},                                                 { "{", "<Statement List>", "}" },           {},             {},                                             {},             {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                 {},                                                                                         {},                 },
/* ROW[11] - <Opt Declaration List>  */         {   {},                                                                                                 { "<Empty>" },                                  {},                                             {},                                             { "<Declaration List>" },                           { "<Declaration List>" },                           { "<Declaration List>" },                           { "<Empty>" },                              {},             {},                                             {},             {},     {},             { "<Empty>" },                                              {},                                 {},         { "<Empty>" },                              { "<Empty>" },                              { "<Empty>" },                              { "<Empty>" },                                          {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                 {},                                                                                         {},                 },
/* ROW[12] - <Declaration List>  */             {   {},                                                                                                 {},                                             {},                                             {},                                             { "<Declaration>", ";", "<Declaration List>\'" },   { "<Declaration>", ";", "<Declaration List>\'" },   { "<Declaration>", ";", "<Declaration List>\'" },   {},                                         {},             {},                                             {},             {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                 {},                                                                                         {},                 },
/* ROW[13] - <Declaration List>' */             {   {},                                                                                                 { "<Empty>" },                                  {},                                             {},                                             { "<Declaration List>" },                           { "<Declaration List>" },                           { "<Declaration List>" },                           { "<Empty>" },                              {},             {},                                             {},             {},     {},             { "<Empty>" },                                              {},                                 {},         { "<Empty>" },                              { "<Empty>" },                              { "<Empty>" },                              { "<Empty>" },                                          {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                 {},                                                                                         {},                 },
/* ROW[14] - <Declaration>  */                  {   {},                                                                                                 {},                                             {},                                             {},                                             { "<Qualifier>", "<IDs>" },                         { "<Qualifier>", "<IDs>" },                         { "<Qualifier>", "<IDs>" },                         {},                                         {},             {},                                             {},             {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                 {},                                                                                         {},                 },
/* ROW[15] - <IDs>  */                          {   {},                                                                                                 { "IDENTIFIER", "<IDs>\'" },                    {},                                             {},                                             {},                                                 {},                                                 {},                                                 {},                                         {},             {},                                             {},             {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             { "<Empty>" },  {},                 {},                                                                                         {},                 },
/* ROW[16] - <IDs>' */                          {   {},                                                                                                 {},                                             {},                                             {},                                             { "<Empty>" },                                      { "<Empty>" },                                      { "<Empty>" },                                      {},                                         {},             {},                                             { "<Empty>" },  {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             { "<Empty>" },  { "<Empty>" },  { ",", "<IDs>" },   {},                                                                                         {},                 },
/* ROW[17] - <Statement List>  */               {   {},                                                                                                 { "<Statement>", "<Statement List>\'" },        {},                                             {},                                             {},                                                 {},                                                 {},                                                 { "<Statement>", "<Statement List>\'" },    {},             {},                                             {},             {},     {},             { "<Statement>", "<Statement List>\'" },                    {},                                 {},         { "<Statement>", "<Statement List>\'" },    { "<Statement>", "<Statement List>\'" },    { "<Statement>", "<Statement List>\'" },    { "<Statement>", "<Statement List>\'" },                {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                 {},                                                                                         {},                 },
/* ROW[18] - <Statement List>' */               {   {},                                                                                                 { "<Statement List>" },                         {},                                             {},                                             {},                                                 {},                                                 {},                                                 { "<Statement List>" },                     { "<Empty>" },  {},                                             {},             {},     {},             { "<Statement List>" },                                     {},                                 {},         { "<Statement List>" },                     { "<Statement List>" },                     { "<Statement List>" },                     { "<Statement List>" },                                 {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                 {},                                                                                         { "<Empty>" },      },
/* ROW[19] - <Statement>  */                    {   {},                                                                                                 { "<Assign>" },                                 {},                                             {},                                             {},                                                 {},                                                 {},                                                 { "<Compound>" },                           {},             {},                                             {},             {},     {},             { "<If>" },                                                 {},                                 {},         { "<Return>" },                             { "<Print>" },                              { "<Scan>" },                               { "<While>" },                                          {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                 {},                                                                                         {},                 },
/* ROW[20] - <Compound>  */                     {   {},                                                                                                 {},                                             {},                                             {},                                             {},                                                 {},                                                 {},                                                 { "{", "<Statement List>", "}" },           {},             {},                                             {},             {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                 {},                                                                                         {},                 },
/* ROW[21] - <Assign>  */                       {   {},                                                                                                 { "IDENTIFIER", "=", "<Expression>", ";" },     {},                                             {},                                             {},                                                 {},                                                 {},                                                 {},                                         {},             {},                                             {},             {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                 {},                                                                                         {},                 },
/* ROW[22] - <If>  */                           {   {},                                                                                                 {},                                             {},                                             {},                                             {},                                                 {},                                                 {},                                                 {},                                         {},             {},                                             {},             {},     {},             { "if", "(", "<Condition>", ")", "<Statement>", "<If>\'" }, {},                                 {},         {},                                         {},                                         {},                                         {},                                                     {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                 {},                                                                                         {},                 },
/* ROW[23] - <If>' */                           {   {},                                                                                                 {},                                             {},                                             {},                                             {},                                                 {},                                                 {},                                                 {},                                         {},             {},                                             {},             {},     {},             {},                                                         { "else", "<Statement>", "endif" }, { "endif"}, {},                                         {},                                         {},                                         {},                                                     {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                 {},                                                                                         {},                 },
/* ROW[24] - <Return>  */                       {   {},                                                                                                 {},                                             {},                                             {},                                             {},                                                 {},                                                 {},                                                 {},                                         {},             {},                                             {},             {},     {},             {},                                                         {},                                 {},         { "return", "<Return>\'" },                 {},                                         {},                                         {},                                                     {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                 {},                                                                                         {},                 },
/* ROW[25] - <Return>' */                       {   {},                                                                                                 { "<Expression>", ";" },                        { "<Expression>", ";" },                        { "<Expression>", ";" },                        {},                                                 {},                                                 {},                                                 {},                                         {},             { "<Expression>", ";" },                        {},             {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     { "<Expression>", ";" },                        { "<Expression>", ";" },                        {},                                     { "<Expression>", ";" },                        {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             { ";" },        {},                 {},                                                                                         {},                 },
/* ROW[26] - <Print>  */                        {   {},                                                                                                 {},                                             {},                                             {},                                             {},                                                 {},                                                 {},                                                 {},                                         {},             {},                                             {},             {},     {},             {},                                                         {},                                 {},         {},                                         { "put", "(",  "<Expression>", ")", ";" },  {},                                         {},                                                     {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                 {},                                                                                         {},                 },
/* ROW[27] - <Scan>  */                         {   {},                                                                                                 {},                                             {},                                             {},                                             {},                                                 {},                                                 {},                                                 {},                                         {},             {},                                             {},             {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         { "get", "(", "<IDs>", ")", ";" },          {},                                                     {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                 {},                                                                                         {},                 },
/* ROW[28] - <While>  */                        {   {},                                                                                                 {},                                             {},                                             {},                                             {},                                                 {},                                                 {},                                                 {},                                         {},             {},                                             {},             {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         { "while", "(", "<Condition>", ")", "<Statement>" },    {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                 {},                                                                                         {},                 },
/* ROW[29] - <Condition>  */                    {   {},                                                                                                 { "<Expression>", "<Relop>", "<Expression>" },  { "<Expression>", "<Relop>", "<Expression>" },  { "<Expression>", "<Relop>", "<Expression>" },  {},                                                 {},                                                 {},                                                 {},                                         {},             { "<Expression>", "<Relop>", "<Expression>" },  {},             {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     { "<Expression>", "<Relop>", "<Expression>" },  { "<Expression>", "<Relop>", "<Expression>" },  {},                                     { "<Expression>", "<Relop>", "<Expression>" },  {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                 {},                                                                                         {},                 },
/* ROW[30] - <Relop>  */                        {   {},                                                                                                 {},                                             {},                                             {},                                             {},                                                 {},                                                 {},                                                 {},                                         {},             {},                                             {},             {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 { "==" },       { "^=" },       { ">" },        { "<" },        { "=>" },       { "=<" },       {},             {},             {},                 {},                                                                                         {},                 },
/* ROW[31] - <Expression>  */                   {   {},                                                                                                 { "<Term>", "<Expression>\'" },                 { "<Term>", "<Expression>\'" },                 { "<Term>", "<Expression>\'" },                 {},                                                 {},                                                 {},                                                 {},                                         {},             { "<Term>", "<Expression>\'" },                 { "<Empty>" },  {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     { "<Term>", "<Expression>\'" },                 { "<Term>", "<Expression>\'" },                 {},                                     { "<Term>", "<Expression>\'" },                 {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                 {},                                                                                         {},                 },
/* ROW[32] - <Expression>' */                   {   {},                                                                                                 {},                                             {},                                             {},                                             {},                                                 {},                                                 {},                                                 {},                                         {},             {},                                             { "<Empty>" },  {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     {},                                             {},                                             { "+", "<Term>", "<Expression>\'" },    { "-", "<Term>", "<Expression>\'" },            {},                                 {},                                 { "<Empty>" },  { "<Empty>" },  { "<Empty>" },  { "<Empty>" },  { "<Empty>" },  { "<Empty>" },  {},             { "<Empty>" },  {},                 {},                                                                                         {},                 },
/* ROW[33] - <Term>  */                         {   {},                                                                                                 { "<Factor>", "<Term>\'" },                     { "<Factor>", "<Term>\'" },                     { "<Factor>", "<Term>\'" },                     {},                                                 {},                                                 {},                                                 {},                                         {},             { "<Factor>", "<Term>\'" },                     {},             {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     { "<Factor>", "<Term>\'" },                     { "<Factor>", "<Term>\'" },                     {},                                     { "<Factor>", "<Term>\'" },                     {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                 {},                                                                                         {},                 },
/* ROW[34] - <Term>' */                         {   {},                                                                                                 {},                                             {},                                             {},                                             {},                                                 {},                                                 {},                                                 {},                                         {},             {},                                             { "<Empty>" },  {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     {},                                             {},                                             { "<Empty>" },                          { "<Empty>" },                                  { "*", "<Factor>", "<Term>\'" },    { "/", "<Factor>", "<Term>\'" },    { "<Empty>" },  { "<Empty>" },  { "<Empty>" },  { "<Empty>" },  { "<Empty>" },  { "<Empty>" },  {},             { "<Empty>" },  {},                 {},                                                                                         {},                 },
/* ROW[35] - <Factor>  */                       {   {},                                                                                                 { "<Primary>" },                                { "<Primary>" },                                { "<Primary>" },                                {},                                                 {},                                                 {},                                                 {},                                         {},             { "<Primary>" },                                {},             {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     { "<Primary>" },                                { "<Primary>" },                                {},                                     { "-", "<Primary>" },                           {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                 {},                                                                                         {},                 },
/* ROW[36] - <Primary>  */                      {   {},                                                                                                 { "IDENTIFIER", "<Primary>\'" },                { "INTEGER" },                                  { "REAL" },                                     {},                                                 {},                                                 {},                                                 {},                                         {},             { "(", "<Expression>", ")" },                   {},             {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     { "true" },                                     { "false" },                                    {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                 {},                                                                                         {},                 },
/* ROW[37] - <Primary>' */                      {   {},                                                                                                 {},                                             {},                                             {},                                             {},                                                 {},                                                 {},                                                 {},                                         {},             { "(", "<IDs>", ")" },                          { "<Empty>" },  {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     {},                                             {},                                             { "<Empty>" },                          { "<Empty>" },                                  { "<Empty>" },                      { "<Empty>" },                      { "<Empty>" },  { "<Empty>" },  { "<Empty>" },  { "<Empty>" },  { "<Empty>" },  { "<Empty>" },  {},             { "<Empty>" },  {},                 {},                                                                                         {},                 },
};

// const unordered_map<string, int> PredictiveParserTable::NONTERMINAL_TO_ROW {
//     {"R01"  ,  0 },
//     {"R02"  ,  1 },
//     {"R03"  ,  2 },
//     {"R03\'",  3 },
//     {"R04"  ,  4 },
//     {"R05"  ,  5 },
//     {"R06"  ,  6 },
//     {"R06\'",  7 },
//     {"R07"  ,  8 },
//     {"R08"  ,  9 },
//     {"R09"  , 10 },
//     {"R10"  , 11 },
//     {"R11"  , 12 },
//     {"R11\'", 13 },
//     {"R12"  , 14 },
//     {"R13"  , 15 },
//     {"R13\'", 16 },
//     {"R14"  , 17 },
//     {"R14\'", 18 },
//     {"R15"  , 19 },
//     {"R16"  , 20 },
//     {"R17"  , 21 },
//     {"R18"  , 22 },
//     {"R18\'", 23 },
//     {"R19"  , 24 },
//     {"R19\'", 25 },
//     {"R20"  , 26 },
//     {"R21"  , 27 },
//     {"R22"  , 28 },
//     {"R23"  , 29 },
//     {"R24"  , 30 },
//     {"R25"  , 31 },
//     {"R25\'", 32 },
//     {"R26"  , 33 },
//     {"R26\'", 34 },
//     {"R27"  , 35 },
//     {"R28"  , 36 },
//     {"R28\'", 37 },
// };

// const vector<vector<vector<string>>> PredictiveParserTable::PREDICTIVE_PARSER_TABLE = {
// /* ROW_INDEX \ COL_INDEX    {   0,                                                              1,                                  2,                          3,                          4,                          5,                          6,                          7,                      8,              9,                          10,             11,     12,             13,                                         14,                         15,         16,                     17,                                 18,                                 19,                                     20,                         21,                         22,                         23,                         24,                         25,                         26,             27,             28,             29,             30,             31,             32,             33,             34,             35,                                 36                  } */
// /* ROW[00] - R01  */        {   { "R02", "%", "%", "R10", "R14"  },                             {},                                 {},                         {},                         {},                         {},                         {},                         {},                     {},             {},                         {},             {},     {},             {},                                         {},                         {},         {},                     {},                                 {},                                 {},                                     {},                         {},                         {},                         {},                         {},                         {},                         {},             {},             {},             {},             {},             {},             {},             {},             {},             { "R02", "%", "%", "R10", "R14" },  { "<Empty>" },      },
// /* ROW[01] - R02  */        {   { "R03"  },                                                     {},                                 {},                         {},                         {},                         {},                         {},                         {},                     {},             {},                         {},             {},     {},             {},                                         {},                         {},         {},                     {},                                 {},                                 {},                                     {},                         {},                         {},                         {},                         {},                         {},                         {},             {},             {},             {},             {},             {},             {},             {},             {},             { "<Empty>" },                      {},                 },
// /* ROW[02] - R03  */        {   { "R04", "R03\'" },                                             {},                                 {},                         {},                         {},                         {},                         {},                         {},                     {},             {},                         {},             {},     {},             {},                                         {},                         {},         {},                     {},                                 {},                                 {},                                     {},                         {},                         {},                         {},                         {},                         {},                         {},             {},             {},             {},             {},             {},             {},             {},             {},             {},                                 {},                 },
// /* ROW[03] - R03' */        {   { "R03" },                                                      {},                                 {},                         {},                         {},                         {},                         {},                         {},                     {},             {},                         {},             {},     {},             {},                                         {},                         {},         {},                     {},                                 {},                                 {},                                     {},                         {},                         {},                         {},                         {},                         {},                         {},             {},             {},             {},             {},             {},             {},             {},             {},             { "<Empty>" },                      {},                 },
// /* ROW[04] - R04  */        {   { "<function>", "IDENTIFIER", "[", "R05", "]", "R10", "R09"},     {},                                 {},                         {},                         {},                         {},                         {},                         {},                     {},             {},                         {},             {},     {},             {},                                         {},                         {},         {},                     {},                                 {},                                 {},                                     {},                         {},                         {},                         {},                         {},                         {},                         {},             {},             {},             {},             {},             {},             {},             {},             {},             {},                                 {},                 },
// /* ROW[05] - R05  */        {   {},                                                             { "R06" },                          {},                         {},                         {},                         {},                         {},                         {},                     {},             {},                         {},             {},     { "<Empty>" },  {},                                         {},                         {},         {},                     {},                                 {},                                 {},                                     {},                         {},                         {},                         {},                         {},                         {},                         {},             {},             {},             {},             {},             {},             {},             {},             {},             {},                                 {},                 },
// /* ROW[06] - R06  */        {   {},                                                             { "R07", "R06\'" },                 {},                         {},                         {},                         {},                         {},                         {},                     {},             {},                         {},             {},     {},             {},                                         {},                         {},         {},                     {},                                 {},                                 {},                                     {},                         {},                         {},                         {},                         {},                         {},                         {},             {},             {},             {},             {},             {},             {},             {},             {},             {},                                 {},                 },
// /* ROW[07] - R06' */        {   {},                                                             { "R06" },                          {},                         {},                         {},                         {},                         {},                         {},                     {},             {},                         {},             {},     { "<Empty>" },  {},                                         {},                         {},         {},                     {},                                 {},                                 {},                                     {},                         {},                         {},                         {},                         {},                         {},                         {},             {},             {},             {},             {},             {},             {},             {},             {},             {},                                 {},                 },
// /* ROW[08] - R07  */        {   {},                                                             { "R13", ":", "R08" },              {},                         {},                         {},                         {},                         {},                         {},                     {},             {},                         {},             {},     {},             {},                                         {},                         {},         {},                     {},                                 {},                                 {},                                     {},                         {},                         {},                         {},                         {},                         {},                         {},             {},             {},             {},             {},             {},             {},             {},             {},             {},                                 {},                 },
// /* ROW[09] - R08  */        {   {},                                                             {},                                 {},                         {},                         { "int" },                  { "boolean" },              { "real" },                 {},                     {},             {},                         {},             {},     {},             {},                                         {},                         {},         {},                     {},                                 {},                                 {},                                     {},                         {},                         {},                         {},                         {},                         {},                         {},             {},             {},             {},             {},             {},             {},             {},             {},             {},                                 {},                 },
// /* ROW[10] - R09  */        {   {},                                                             {},                                 {},                         {},                         {},                         {},                         {},                         { "{", "R14", "}" },    {},             {},                         {},             {},     {},             {},                                         {},                         {},         {},                     {},                                 {},                                 {},                                     {},                         {},                         {},                         {},                         {},                         {},                         {},             {},             {},             {},             {},             {},             {},             {},             {},             {},                                 {},                 },
// /* ROW[11] - R10  */        {   {},                                                             { "<Empty>" },                      {},                         {},                         { "R11" },                  { "R11" },                  { "R11" },                  { "<Empty>" },          {},             {},                         {},             {},     {},             { "<Empty>" },                              {},                         {},         { "<Empty>" },          { "<Empty>" },                      { "<Empty>" },                      { "<Empty>" },                          {},                         {},                         {},                         {},                         {},                         {},                         {},             {},             {},             {},             {},             {},             {},             {},             {},             {},                                 {},                 },
// /* ROW[12] - R11  */        {   {},                                                             {},                                 {},                         {},                         { "R12", ";", "R11\'" },    { "R12", ";", "R11\'" },    { "R12", ";", "R11\'" },    {},                     {},             {},                         {},             {},     {},             {},                                         {},                         {},         {},                     {},                                 {},                                 {},                                     {},                         {},                         {},                         {},                         {},                         {},                         {},             {},             {},             {},             {},             {},             {},             {},             {},             {},                                 {},                 },
// /* ROW[13] - R11' */        {   {},                                                             { "<Empty>" },                      {},                         {},                         { "R11" },                  { "R11" },                  { "R11" },                  { "<Empty>" },          {},             {},                         {},             {},     {},             { "<Empty>" },                              {},                         {},         { "<Empty>" },          { "<Empty>" },                      { "<Empty>" },                      { "<Empty>" },                          {},                         {},                         {},                         {},                         {},                         {},                         {},             {},             {},             {},             {},             {},             {},             {},             {},             {},                                 {},                 },
// /* ROW[14] - R12  */        {   {},                                                             {},                                 {},                         {},                         { "R08", "R13" },           { "R08", "R13" },           { "R08", "R13" },           {},                     {},             {},                         {},             {},     {},             {},                                         {},                         {},         {},                     {},                                 {},                                 {},                                     {},                         {},                         {},                         {},                         {},                         {},                         {},             {},             {},             {},             {},             {},             {},             {},             {},             {},                                 {},                 },
// /* ROW[15] - R13  */        {   {},                                                             { "IDENTIFIER", "R13\'" },          {},                         {},                         {},                         {},                         {},                         {},                     {},             {},                         {},             {},     {},             {},                                         {},                         {},         {},                     {},                                 {},                                 {},                                     {},                         {},                         {},                         {},                         {},                         {},                         {},             {},             {},             {},             {},             {},             {},             { "<Empty>" },  {},             {},                                 {},                 },
// /* ROW[16] - R13' */        {   {},                                                             {},                                 {},                         {},                         { "<Empty>" },              { "<Empty>" },              { "<Empty>" },              {},                     {},             {},                         { "<Empty>" },  {},     {},             {},                                         {},                         {},         {},                     {},                                 {},                                 {},                                     {},                         {},                         {},                         {},                         {},                         {},                         {},             {},             {},             {},             {},             {},             { "<Empty>" },  { "<Empty>" },  { ",", "R13" }, {},                                 {},                 },
// /* ROW[17] - R14  */        {   {},                                                             { "R15", "R14\'" },                 {},                         {},                         {},                         {},                         {},                         { "R15", "R14\'" },     {},             {},                         {},             {},     {},             { "R15", "R14\'" },                         {},                         {},         { "R15", "R14\'" },     { "R15", "R14\'" },                 { "R15", "R14\'" },                 { "R15", "R14\'" },                     {},                         {},                         {},                         {},                         {},                         {},                         {},             {},             {},             {},             {},             {},             {},             {},             {},             {},                                 {},                 },
// /* ROW[18] - R14' */        {   {},                                                             { "R14" },                          {},                         {},                         {},                         {},                         {},                         { "R14" },              { "<Empty>" },  {},                         {},             {},     {},             { "R14" },                                  {},                         {},         { "R14" },              { "R14" },                          { "R14" },                          { "R14" },                              {},                         {},                         {},                         {},                         {},                         {},                         {},             {},             {},             {},             {},             {},             {},             {},             {},             {},                                 { "<Empty>" },      },
// /* ROW[19] - R15  */        {   {},                                                             { "R17" },                          {},                         {},                         {},                         {},                         {},                         { "R16" },              {},             {},                         {},             {},     {},             { "R18" },                                  {},                         {},         { "R19" },              { "R20" },                          { "R21" },                          { "R22" },                              {},                         {},                         {},                         {},                         {},                         {},                         {},             {},             {},             {},             {},             {},             {},             {},             {},             {},                                 {},                 },
// /* ROW[20] - R16  */        {   {},                                                             {},                                 {},                         {},                         {},                         {},                         {},                         { "{", "R14", "}" },    {},             {},                         {},             {},     {},             {},                                         {},                         {},         {},                     {},                                 {},                                 {},                                     {},                         {},                         {},                         {},                         {},                         {},                         {},             {},             {},             {},             {},             {},             {},             {},             {},             {},                                 {},                 },
// /* ROW[21] - R17  */        {   {},                                                             { "IDENTIFIER", "=", "R25", ";" },  {},                         {},                         {},                         {},                         {},                         {},                     {},             {},                         {},             {},     {},             {},                                         {},                         {},         {},                     {},                                 {},                                 {},                                     {},                         {},                         {},                         {},                         {},                         {},                         {},             {},             {},             {},             {},             {},             {},             {},             {},             {},                                 {},                 },
// /* ROW[22] - R18  */        {   {},                                                             {},                                 {},                         {},                         {},                         {},                         {},                         {},                     {},             {},                         {},             {},     {},             { "if", "(", "R23", ")", "R15", "R18\'" },  {},                         {},         {},                     {},                                 {},                                 {},                                     {},                         {},                         {},                         {},                         {},                         {},                         {},             {},             {},             {},             {},             {},             {},             {},             {},             {},                                 {},                 },
// /* ROW[23] - R18' */        {   {},                                                             {},                                 {},                         {},                         {},                         {},                         {},                         {},                     {},             {},                         {},             {},     {},             {},                                         { "else", "R15", "endif" }, { "endif"}, {},                     {},                                 {},                                 {},                                     {},                         {},                         {},                         {},                         {},                         {},                         {},             {},             {},             {},             {},             {},             {},             {},             {},             {},                                 {},                 },
// /* ROW[24] - R19  */        {   {},                                                             {},                                 {},                         {},                         {},                         {},                         {},                         {},                     {},             {},                         {},             {},     {},             {},                                         {},                         {},         { "return", "R19\'" },  {},                                 {},                                 {},                                     {},                         {},                         {},                         {},                         {},                         {},                         {},             {},             {},             {},             {},             {},             {},             {},             {},             {},                                 {},                 },
// /* ROW[25] - R19' */        {   {},                                                             { "R25", ";" },                     { "R25", ";" },             { "R25", ";" },             {},                         {},                         {},                         {},                     {},             { "R25", ";" },             {},             {},     {},             {},                                         {},                         {},         {},                     {},                                 {},                                 {},                                     { "R25", ";" },             { "R25", ";" },             {},                         { "R25", ";" },             {},                         {},                         {},             {},             {},             {},             {},             {},             {},             { ";" },        {},             {},                                 {},                 },
// /* ROW[26] - R20  */        {   {},                                                             {},                                 {},                         {},                         {},                         {},                         {},                         {},                     {},             {},                         {},             {},     {},             {},                                         {},                         {},         {},                     { "put", "(",  "R25", ")", ";" },   {},                                 {},                                     {},                         {},                         {},                         {},                         {},                         {},                         {},             {},             {},             {},             {},             {},             {},             {},             {},             {},                                 {},                 },
// /* ROW[27] - R21  */        {   {},                                                             {},                                 {},                         {},                         {},                         {},                         {},                         {},                     {},             {},                         {},             {},     {},             {},                                         {},                         {},         {},                     {},                                 { "get", "(", "R13", ")", ";" },    {},                                     {},                         {},                         {},                         {},                         {},                         {},                         {},             {},             {},             {},             {},             {},             {},             {},             {},             {},                                 {},                 },
// /* ROW[28] - R22  */        {   {},                                                             {},                                 {},                         {},                         {},                         {},                         {},                         {},                     {},             {},                         {},             {},     {},             {},                                         {},                         {},         {},                     {},                                 {},                                 { "while", "(", "R23", ")", "R15" },    {},                         {},                         {},                         {},                         {},                         {},                         {},             {},             {},             {},             {},             {},             {},             {},             {},             {},                                 {},                 },
// /* ROW[29] - R23  */        {   {},                                                             { "R25", "R24", "R25" },            { "R25", "R24", "R25" },    { "R25", "R24", "R25" },    {},                         {},                         {},                         {},                     {},             { "R25", "R24", "R25" },    {},             {},     {},             {},                                         {},                         {},         {},                     {},                                 {},                                 {},                                     { "R25", "R24", "R25" },    { "R25", "R24", "R25" },    {},                         { "R25", "R24", "R25" },    {},                         {},                         {},             {},             {},             {},             {},             {},             {},             {},             {},             {},                                 {},                 },
// /* ROW[30] - R24  */        {   {},                                                             {},                                 {},                         {},                         {},                         {},                         {},                         {},                     {},             {},                         {},             {},     {},             {},                                         {},                         {},         {},                     {},                                 {},                                 {},                                     {},                         {},                         {},                         {},                         {},                         {},                         { "==" },       { "^=" },       { ">" },        { "<" },        { "=>" },       { "=<" },       {},             {},             {},             {},                                 {},                 },
// /* ROW[31] - R25  */        {   {},                                                             { "R26", "R25\'" },                 { "R26", "R25\'" },         { "R26", "R25\'" },         {},                         {},                         {},                         {},                     {},             { "R26", "R25\'" },         { "<Empty>" },  {},     {},             {},                                         {},                         {},         {},                     {},                                 {},                                 {},                                     { "R26", "R25\'" },         { "R26", "R25\'" },         {},                         { "R26", "R25\'" },         {},                         {},                         {},             {},             {},             {},             {},             {},             {},             {},             {},             {},                                 {},                 },
// /* ROW[32] - R25' */        {   {},                                                             {},                                 {},                         {},                         {},                         {},                         {},                         {},                     {},             {},                         { "<Empty>" },  {},     {},             {},                                         {},                         {},         {},                     {},                                 {},                                 {},                                     {},                         {},                         { "+", "R26", "R25\'" },    { "-", "R26", "R25\'" },    {},                         {},                         { "<Empty>" },  { "<Empty>" },  { "<Empty>" },  { "<Empty>" },  { "<Empty>" },  { "<Empty>" },  {},             { "<Empty>" },  {},             {},                                 {},                 },
// /* ROW[33] - R26  */        {   {},                                                             { "R27", "R26\'" },                 { "R27", "R26\'" },         { "R27", "R26\'" },         {},                         {},                         {},                         {},                     {},             { "R27", "R26\'" },         {},             {},     {},             {},                                         {},                         {},         {},                     {},                                 {},                                 {},                                     { "R27", "R26\'" },         { "R27", "R26\'" },         {},                         { "R27", "R26\'" },         {},                         {},                         {},             {},             {},             {},             {},             {},             {},             {},             {},             {},                                 {},                 },
// /* ROW[34] - R26' */        {   {},                                                             {},                                 {},                         {},                         {},                         {},                         {},                         {},                     {},             {},                         { "<Empty>" },  {},     {},             {},                                         {},                         {},         {},                     {},                                 {},                                 {},                                     {},                         {},                         { "<Empty>" },              { "<Empty>" },              { "*", "R27", "R26\'" },    { "/", "R27", "R26\'" },    { "<Empty>" },  { "<Empty>" },  { "<Empty>" },  { "<Empty>" },  { "<Empty>" },  { "<Empty>" },  {},             { "<Empty>" },  {},             {},                                 {},                 },
// /* ROW[35] - R27  */        {   {},                                                             { "R28" },                          { "R28" },                  { "R28" },                  {},                         {},                         {},                         {},                     {},             { "R28" },                  {},             {},     {},             {},                                         {},                         {},         {},                     {},                                 {},                                 {},                                     { "R28" },                  { "R28" },                  {},                         { "-", "R28" },             {},                         {},                         {},             {},             {},             {},             {},             {},             {},             {},             {},             {},                                 {},                 },
// /* ROW[36] - R28  */        {   {},                                                             { "IDENTIFIER", "R28\'" },          { "INTEGER" },              { "REAL" },                 {},                         {},                         {},                         {},                     {},             { "(", "R25", ")" },        {},             {},     {},             {},                                         {},                         {},         {},                     {},                                 {},                                 {},                                     { "true" },                 { "false" },                {},                         {},                         {},                         {},                         {},             {},             {},             {},             {},             {},             {},             {},             {},             {},                                 {},                 },
// /* ROW[37] - R28' */        {   {},                                                             {},                                 {},                         {},                         {},                         {},                         {},                         {},                     {},             { "(", "R13", ")" },        { "<Empty>" },  {},     {},             {},                                         {},                         {},         {},                     {},                                 {},                                 {},                                     {},                         {},                         { "<Empty>" },              { "<Empty>" },              { "<Empty>" },              { "<Empty>" },              { "<Empty>" },  { "<Empty>" },  { "<Empty>" },  { "<Empty>" },  { "<Empty>" },  { "<Empty>" },  {},             { "<Empty>" },  {},             {},                                 {},                 },
// };

#endif // PARSER_TABLE_CPP