#ifndef PARSER_TABLE_CPP
#define PARSER_TABLE_CPP

#include "./LL_ParserTable.h"

const vector<string> PredictiveParserTable::get_next_step(string lhs, string incoming_token) const {
    int row = -1;
    int col = -1;

    try {
        row = NONTERMINAL_TO_ROW.at(lhs);
        col = TERMINAL_TO_COL.at(incoming_token);
    } catch (const std::out_of_range& oor) {
        std::cerr << "Out of Range error in PARSER_TABLE: " << oor.what() << '\n';
        return vector<string>();
    }

    return PREDICTIVE_PARSER_TABLE[row][col];
}

const unordered_map<string, int> PredictiveParserTable::NONTERMINAL_TO_ROW {
    {"<Rat23S>"  ,                       0 },
    {"<Opt Function Definitions>"  ,     1 },
    {"<Function Definitions>"  ,         2 },
    {"<Function Definitions>\'",         3 },
    {"<Function>"  ,                     4 },
    {"<Opt Parameter List>"  ,           5 },
    {"<Parameter List>"  ,               6 },
    {"<Parameter List>'",                7 },
    {"<Parameter>"  ,                    8 },
    {"<Qualifier>"  ,                    9 },
    {"<Body>"  ,                        10 },
    {"<Opt Declaration List>"  ,        11 },
    {"<Declaration List>"  ,            12 },
    {"<Declaration List>\'",            13 },
    {"<Declaration>"  ,                 14 },
    {"<IDs>"  ,                         15 },
    {"<IDs>\'",                         16 },
    {"<Statement List>"  ,              17 },
    {"<Statement List>\'",              18 },
    {"<Statement>"  ,                   19 },
    {"<Compound>"  ,                    20 },
    {"<Assign>"  ,                      21 },
    {"<If>"  ,                          22 },
    {"<If>\'",                          23 },
    {"<Return>"  ,                      24 },
    {"<Return>\'",                      25 },
    {"<Print>"  ,                       26 },
    {"<Scan>"  ,                        27 },
    {"<While>"  ,                       28 },
    {"<Condition>"  ,                   29 },
    {"<Relop>"  ,                       30 },
    {"<Expression>"  ,                  31 },
    {"<Expression>\'",                  32 },
    {"<Term>"  ,                        33 },
    {"<Term>\'",                        34 },
    {"<Factor>"  ,                      35 },
    {"<Primary>"  ,                     36 },
    {"<Primary>\'",                     37 },
};

// predictive parser table column dicitonary
const unordered_map<string, int> PredictiveParserTable::TERMINAL_TO_COL {
    // GENERALIZED TERMINALS
    { "IDENTIFIER", 1 }, { "INTEGER", 2 }, { "REAL", 3 },
    
    // KEYWORDS
    { "function", 0 }, { "int", 4 }, { "boolean", 5 }, { "real", 6 }, { "if", 13 }, { "else", 14 }, { "endif", 15 }, {"return", 16}, { "put", 17 }, { "get", 18 }, { "while", 19 },

    // BOOLEAN VALUE
    { "true", 20 }, { "false", 21 },

    // OPERATORS
    { "+", 22 }, { "-", 23 }, { "*", 24 }, { "/", 25 }, { "==", 26 }, { "^=", 27 }, { ">", 28 }, { "<", 29 }, { "=>", 30 }, { "=<", 31 },

    // SEPARATORS
    { "{", 7 }, { "}", 8}, { "(", 9 }, { ")", 10 }, { "[", 11 }, { "]", 12 }, { ":", 32 }, { ";", 33 }, { ",", 34 }, { "%", 35 }, { "$", 36 }
};

const vector<vector<vector<string>>> PredictiveParserTable::PREDICTIVE_PARSER_TABLE = {
/* ROW_INDEX \ COL_INDEX                        {   0                                                                                                   1,                                              2,                                              3,                                              4,                                                  5,                                                  6,                                                  7,                                          8,              9,                                              10,             11,     12,             13,                                                         14,                                 15,         16,                                         17,                                         18,                                         19,                                                     20,                                             21,                                             22,                                     23,                                             24,                                 25,                                 26,             27,             28,             29,             30,             31,             32,             33,             34,                             35,                                                                                         36                  } */
/* ROW[00] - <Rat23S>  */                       {   { "<Opt Function Definitions>", "%", "%", "<Opt Declaration List>", "<Statement List>"  },          {},                                             {},                                             {},                                             {},                                                 {},                                                 {},                                                 {},                                         {},             {},                                             {},             {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                             { "<Opt Function Definitions>", "%", "%", "<Opt Declaration List>", "<Statement List>" },   { "<Empty>" },      },
/* ROW[01] - <Opt Function Definitions>  */     {   { "<Function Definitions>"  },                                                                      {},                                             {},                                             {},                                             {},                                                 {},                                                 {},                                                 {},                                         {},             {},                                             {},             {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                             { "<Empty>" },                                                                              {},                 },
/* ROW[02] - <Function Definitions>  */         {   { "<Function>", "<Function Definitions>\'" },                                                       {},                                             {},                                             {},                                             {},                                                 {},                                                 {},                                                 {},                                         {},             {},                                             {},             {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                             {},                                                                                         {},                 },
/* ROW[03] - <Function Definitions>' */         {   { "<Function Definitions>" },                                                                       {},                                             {},                                             {},                                             {},                                                 {},                                                 {},                                                 {},                                         {},             {},                                             {},             {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                             { "<Empty>" },                                                                              {},                 },
/* ROW[04] - Function  */                       {   { "function", "IDENTIFIER", "[", "<Opt Parameter List>", "]", "<Opt Declaration List>", "<Body>"},  {},                                             {},                                             {},                                             {},                                                 {},                                                 {},                                                 {},                                         {},             {},                                             {},             {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                             {},                                                                                         {},                 },
/* ROW[05] - <Opt Parameter List>  */           {   {},                                                                                                 { "<Parameter List>" },                         {},                                             {},                                             {},                                                 {},                                                 {},                                                 {},                                         {},             {},                                             {},             {},     { "<Empty>" },  {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                             {},                                                                                         {},                 },
/* ROW[06] - <Parameter List>  */               {   {},                                                                                                 { "<Parameter>", "<Parameter List>'" },         {},                                             {},                                             {},                                                 {},                                                 {},                                                 {},                                         {},             {},                                             {},             {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                             {},                                                                                         {},                 },
/* ROW[07] - <Parameter List>' */               {   {},                                                                                                 { "<Parameter List>" },                         {},                                             {},                                             {},                                                 {},                                                 {},                                                 {},                                         {},             {},                                             {},             {},     { "<Empty>" },  {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             { ",", "<Parameter List>" },    {},                                                                                         {},                 },
/* ROW[08] - <Parameter>  */                    {   {},                                                                                                 { "<IDs>", ":", "<Qualifier>" },                {},                                             {},                                             {},                                                 {},                                                 {},                                                 {},                                         {},             {},                                             {},             {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                             {},                                                                                         {},                 },
/* ROW[09] - <Qualifier>  */                    {   {},                                                                                                 {},                                             {},                                             {},                                             { "int" },                                          { "boolean" },                                      { "real" },                                         {},                                         {},             {},                                             {},             {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                             {},                                                                                         {},                 },
/* ROW[10] - <Body>  */                         {   {},                                                                                                 {},                                             {},                                             {},                                             {},                                                 {},                                                 {},                                                 { "{", "<Statement List>", "}" },           {},             {},                                             {},             {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                             {},                                                                                         {},                 },
/* ROW[11] - <Opt Declaration List>  */         {   {},                                                                                                 { "<Empty>" },                                  {},                                             {},                                             { "<Declaration List>" },                           { "<Declaration List>" },                           { "<Declaration List>" },                           { "<Empty>" },                              {},             {},                                             {},             {},     {},             { "<Empty>" },                                              {},                                 {},         { "<Empty>" },                              { "<Empty>" },                              { "<Empty>" },                              { "<Empty>" },                                          {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                             {},                                                                                         {},                 },
/* ROW[12] - <Declaration List>  */             {   {},                                                                                                 {},                                             {},                                             {},                                             { "<Declaration>", ";", "<Declaration List>\'" },   { "<Declaration>", ";", "<Declaration List>\'" },   { "<Declaration>", ";", "<Declaration List>\'" },   {},                                         {},             {},                                             {},             {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                             {},                                                                                         {},                 },
/* ROW[13] - <Declaration List>' */             {   {},                                                                                                 { "<Empty>" },                                  {},                                             {},                                             { "<Declaration List>" },                           { "<Declaration List>" },                           { "<Declaration List>" },                           { "<Empty>" },                              {},             {},                                             {},             {},     {},             { "<Empty>" },                                              {},                                 {},         { "<Empty>" },                              { "<Empty>" },                              { "<Empty>" },                              { "<Empty>" },                                          {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                             {},                                                                                         {},                 },
/* ROW[14] - <Declaration>  */                  {   {},                                                                                                 {},                                             {},                                             {},                                             { "<Qualifier>", "<IDs>" },                         { "<Qualifier>", "<IDs>" },                         { "<Qualifier>", "<IDs>" },                         {},                                         {},             {},                                             {},             {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                             {},                                                                                         {},                 },
/* ROW[15] - <IDs>  */                          {   {},                                                                                                 { "IDENTIFIER", "<IDs>\'" },                    {},                                             {},                                             {},                                                 {},                                                 {},                                                 {},                                         {},             {},                                             {},             {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             { "<Empty>" },  {},                             {},                                                                                         {},                 },
/* ROW[16] - <IDs>' */                          {   {},                                                                                                 {},                                             {},                                             {},                                             { "<Empty>" },                                      { "<Empty>" },                                      { "<Empty>" },                                      {},                                         {},             {},                                             { "<Empty>" },  {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             { "<Empty>" },  { "<Empty>" },  { ",", "<IDs>" },               {},                                                                                         {},                 },
/* ROW[17] - <Statement List>  */               {   {},                                                                                                 { "<Statement>", "<Statement List>\'" },        {},                                             {},                                             {},                                                 {},                                                 {},                                                 { "<Statement>", "<Statement List>\'" },    {},             {},                                             {},             {},     {},             { "<Statement>", "<Statement List>\'" },                    {},                                 {},         { "<Statement>", "<Statement List>\'" },    { "<Statement>", "<Statement List>\'" },    { "<Statement>", "<Statement List>\'" },    { "<Statement>", "<Statement List>\'" },                {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                             {},                                                                                         {},                 },
/* ROW[18] - <Statement List>' */               {   {},                                                                                                 { "<Statement List>" },                         {},                                             {},                                             {},                                                 {},                                                 {},                                                 { "<Statement List>" },                     { "<Empty>" },  {},                                             {},             {},     {},             { "<Statement List>" },                                     {},                                 {},         { "<Statement List>" },                     { "<Statement List>" },                     { "<Statement List>" },                     { "<Statement List>" },                                 {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                             {},                                                                                         { "<Empty>" },      },
/* ROW[19] - <Statement>  */                    {   {},                                                                                                 { "<Assign>" },                                 {},                                             {},                                             {},                                                 {},                                                 {},                                                 { "<Compound>" },                           {},             {},                                             {},             {},     {},             { "<If>" },                                                 {},                                 {},         { "<Return>" },                             { "<Print>" },                              { "<Scan>" },                               { "<While>" },                                          {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                             {},                                                                                         {},                 },
/* ROW[20] - <Compound>  */                     {   {},                                                                                                 {},                                             {},                                             {},                                             {},                                                 {},                                                 {},                                                 { "{", "<Statement List>", "}" },           {},             {},                                             {},             {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                             {},                                                                                         {},                 },
/* ROW[21] - <Assign>  */                       {   {},                                                                                                 { "IDENTIFIER", "=", "<Expression>", ";" },     {},                                             {},                                             {},                                                 {},                                                 {},                                                 {},                                         {},             {},                                             {},             {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                             {},                                                                                         {},                 },
/* ROW[22] - <If>  */                           {   {},                                                                                                 {},                                             {},                                             {},                                             {},                                                 {},                                                 {},                                                 {},                                         {},             {},                                             {},             {},     {},             { "if", "(", "<Condition>", ")", "<Statement>", "<If>\'" }, {},                                 {},         {},                                         {},                                         {},                                         {},                                                     {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                             {},                                                                                         {},                 },
/* ROW[23] - <If>' */                           {   {},                                                                                                 {},                                             {},                                             {},                                             {},                                                 {},                                                 {},                                                 {},                                         {},             {},                                             {},             {},     {},             {},                                                         { "else", "<Statement>", "endif" }, { "endif"}, {},                                         {},                                         {},                                         {},                                                     {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                             {},                                                                                         {},                 },
/* ROW[24] - <Return>  */                       {   {},                                                                                                 {},                                             {},                                             {},                                             {},                                                 {},                                                 {},                                                 {},                                         {},             {},                                             {},             {},     {},             {},                                                         {},                                 {},         { "return", "<Return>\'" },                 {},                                         {},                                         {},                                                     {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                             {},                                                                                         {},                 },
/* ROW[25] - <Return>' */                       {   {},                                                                                                 { "<Expression>", ";" },                        { "<Expression>", ";" },                        { "<Expression>", ";" },                        {},                                                 {},                                                 {},                                                 {},                                         {},             { "<Expression>", ";" },                        {},             {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     { "<Expression>", ";" },                        { "<Expression>", ";" },                        {},                                     { "<Expression>", ";" },                        {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             { ";" },        {},                             {},                                                                                         {},                 },
/* ROW[26] - <Print>  */                        {   {},                                                                                                 {},                                             {},                                             {},                                             {},                                                 {},                                                 {},                                                 {},                                         {},             {},                                             {},             {},     {},             {},                                                         {},                                 {},         {},                                         { "put", "(",  "<Expression>", ")", ";" },  {},                                         {},                                                     {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                             {},                                                                                         {},                 },
/* ROW[27] - <Scan>  */                         {   {},                                                                                                 {},                                             {},                                             {},                                             {},                                                 {},                                                 {},                                                 {},                                         {},             {},                                             {},             {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         { "get", "(", "<IDs>", ")", ";" },          {},                                                     {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                             {},                                                                                         {},                 },
/* ROW[28] - <While>  */                        {   {},                                                                                                 {},                                             {},                                             {},                                             {},                                                 {},                                                 {},                                                 {},                                         {},             {},                                             {},             {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         { "while", "(", "<Condition>", ")", "<Statement>" },    {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                             {},                                                                                         {},                 },
/* ROW[29] - <Condition>  */                    {   {},                                                                                                 { "<Expression>", "<Relop>", "<Expression>" },  { "<Expression>", "<Relop>", "<Expression>" },  { "<Expression>", "<Relop>", "<Expression>" },  {},                                                 {},                                                 {},                                                 {},                                         {},             { "<Expression>", "<Relop>", "<Expression>" },  {},             {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     { "<Expression>", "<Relop>", "<Expression>" },  { "<Expression>", "<Relop>", "<Expression>" },  {},                                     { "<Expression>", "<Relop>", "<Expression>" },  {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                             {},                                                                                         {},                 },
/* ROW[30] - <Relop>  */                        {   {},                                                                                                 {},                                             {},                                             {},                                             {},                                                 {},                                                 {},                                                 {},                                         {},             {},                                             {},             {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     {},                                             {},                                             {},                                     {},                                             {},                                 {},                                 { "==" },       { "^=" },       { ">" },        { "<" },        { "=>" },       { "=<" },       {},             {},             {},                             {},                                                                                         {},                 },
/* ROW[31] - <Expression>  */                   {   {},                                                                                                 { "<Term>", "<Expression>\'" },                 { "<Term>", "<Expression>\'" },                 { "<Term>", "<Expression>\'" },                 {},                                                 {},                                                 {},                                                 {},                                         {},             { "<Term>", "<Expression>\'" },                 { "<Empty>" },  {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     { "<Term>", "<Expression>\'" },                 { "<Term>", "<Expression>\'" },                 {},                                     { "<Term>", "<Expression>\'" },                 {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                             {},                                                                                         {},                 },
/* ROW[32] - <Expression>' */                   {   {},                                                                                                 {},                                             {},                                             {},                                             {},                                                 {},                                                 {},                                                 {},                                         {},             {},                                             { "<Empty>" },  {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     {},                                             {},                                             { "+", "<Term>", "<Expression>\'" },    { "-", "<Term>", "<Expression>\'" },            {},                                 {},                                 { "<Empty>" },  { "<Empty>" },  { "<Empty>" },  { "<Empty>" },  { "<Empty>" },  { "<Empty>" },  {},             { "<Empty>" },  {},                             {},                                                                                         {},                 },
/* ROW[33] - <Term>  */                         {   {},                                                                                                 { "<Factor>", "<Term>\'" },                     { "<Factor>", "<Term>\'" },                     { "<Factor>", "<Term>\'" },                     {},                                                 {},                                                 {},                                                 {},                                         {},             { "<Factor>", "<Term>\'" },                     {},             {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     { "<Factor>", "<Term>\'" },                     { "<Factor>", "<Term>\'" },                     {},                                     { "<Factor>", "<Term>\'" },                     {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                             {},                                                                                         {},                 },
/* ROW[34] - <Term>' */                         {   {},                                                                                                 {},                                             {},                                             {},                                             {},                                                 {},                                                 {},                                                 {},                                         {},             {},                                             { "<Empty>" },  {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     {},                                             {},                                             { "<Empty>" },                          { "<Empty>" },                                  { "*", "<Factor>", "<Term>\'" },    { "/", "<Factor>", "<Term>\'" },    { "<Empty>" },  { "<Empty>" },  { "<Empty>" },  { "<Empty>" },  { "<Empty>" },  { "<Empty>" },  {},             { "<Empty>" },  {},                             {},                                                                                         {},                 },
/* ROW[35] - <Factor>  */                       {   {},                                                                                                 { "<Primary>" },                                { "<Primary>" },                                { "<Primary>" },                                {},                                                 {},                                                 {},                                                 {},                                         {},             { "<Primary>" },                                {},             {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     { "<Primary>" },                                { "<Primary>" },                                {},                                     { "-", "<Primary>" },                           {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                             {},                                                                                         {},                 },
/* ROW[36] - <Primary>  */                      {   {},                                                                                                 { "IDENTIFIER", "<Primary>\'" },                { "INTEGER" },                                  { "REAL" },                                     {},                                                 {},                                                 {},                                                 {},                                         {},             { "(", "<Expression>", ")" },                   {},             {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     { "true" },                                     { "false" },                                    {},                                     {},                                             {},                                 {},                                 {},             {},             {},             {},             {},             {},             {},             {},             {},                             {},                                                                                         {},                 },
/* ROW[37] - <Primary>' */                      {   {},                                                                                                 {},                                             {},                                             {},                                             {},                                                 {},                                                 {},                                                 {},                                         {},             { "(", "<IDs>", ")" },                          { "<Empty>" },  {},     {},             {},                                                         {},                                 {},         {},                                         {},                                         {},                                         {},                                                     {},                                             {},                                             { "<Empty>" },                          { "<Empty>" },                                  { "<Empty>" },                      { "<Empty>" },                      { "<Empty>" },  { "<Empty>" },  { "<Empty>" },  { "<Empty>" },  { "<Empty>" },  { "<Empty>" },  {},             { "<Empty>" },  {},                             {},                                                                                         {},                 },
};

#endif // PARSER_TABLE_CPP